### ISSUE TITLE
nextflow documentation

### ISSUE THREAD

**Issue by gianfilippo** [genepi/mtdna-server-2#19]
Hi,

is there a documentation or help for the command line version ?

Thanks

**Comment by seppinho** [comment]
Hi @gianfilippo,
Excellent point. Right now we provide some [Nextflow test files](https://github.com/genepi/mtdna-server-2/blob/main/tests/test_mitohpc_fusion.config). I'll add a richer documentation on how to run it on the command-line!

**Comment by charliebidgood** [comment]
> Hi @gianfilippo, Excellent point. Right now we provide some [Nextflow test files](https://github.com/genepi/mtdna-server-2/blob/main/tests/test_mitohpc_fusion.config). I'll add a richer documentation on how to run it on the command-line!

Hi @seppinho, I also just wanted to reiterate (without opening up a new issue) that some additional CLI documentation for the docker/nextflow set up would be really handy. It looks like this may have been present until recent commit?: [7edc3a8](https://github.com/genepi/mtdna-server-2/commit/7edc3a8bdc3b4a1d89530abac919ba00c92509c6). 

On that note, I also think some documentation for using singularity would also be beneficial in the readme seeing as local installations of mtDNA-server-2 may be running on HPCs which don't allow docker. I'm planning on integrating this tool into a larger pipeline (also utilizing singularity) so I would be more than happy to make a pull request addressing this once I'm more familiar with your tool if that would be of any use. Cheers!

**Comment by gianfilippo** [comment]
Thanks. I look forward to the documentation.

**Comment by seppinho** [comment]
Hi all,
The Nextflow documentation has now been added!
https://github.com/genepi/mtdna-server-2?tab=readme-ov-file#local-execution

**Comment by gianfilippo** [comment]
Thanks!!
