### ISSUE TITLE
no-home option error

### ISSUE THREAD

**Issue by fmurgia** [genepi/mtdna-server-2#20]
HI,
I ran the pipeline in my server (nextflow run genepi/mtdna-server-2 -r v2.1.9 -profile test,singularity) using your test dataset and I get this error: "ERROR: Unknown option: --no-home"

Can you help with this?

nextflow run genepi/mtdna-server-2 -r v2.1.9 -profile test,singularity
Nextflow 24.04.1 is available - Please consider updating your version to it
N E X T F L O W  ~  version 23.10.1
Launching `https://github.com/genepi/mtdna-server-2` [irreverent_jepsen] DSL2 - revision: 1140d5c7fd [v2.1.9]
Welcome to mtDNA-Server 2 v2.1.9
(c) Sebastian Schönherr, Hansi Weissensteiner, Lukas Forer
WARN: Access to undefined parameter `output_reports` -- Initialise it to a default value eg. `params.output_reports = some_value`
executor >  local (2)
[be/5d16b1] process > MTDNA_SERVER_2:INDEX                     [100%] 1 of 1, failed: 1 ✘
[20/03d34c] process > MTDNA_SERVER_2:CALCULATE_STATISTICS (1)  [100%] 1 of 1, failed: 1 ✘
[-        ] process > MTDNA_SERVER_2:INPUT_VALIDATION          -
[-        ] process > MTDNA_SERVER_2:QUALITY_CONTROL           -
[-        ] process > MTDNA_SERVER_2:MUTSERVE                  -
[-        ] process > MTDNA_SERVER_2:MUTECT2                   -
[-        ] process > MTDNA_SERVER_2:FILTER_VARIANTS           -
[-        ] process > MTDNA_SERVER_2:MERGING_VARIANTS          -
[-        ] process > MTDNA_SERVER_2:VCF_MERGE                 -
[-        ] process > MTDNA_SERVER_2:HAPLOGROUPS_CONTAMINATION -
[-        ] process > MTDNA_SERVER_2:COVERAGE_ESTIMATION       -
[-        ] process > MTDNA_SERVER_2:ANNOTATE                  -
[-        ] process > MTDNA_SERVER_2:REPORT                    -
[-        ] process > MTDNA_SERVER_2:SAMPLE_REPORT             -
ERROR ~ Error executing process > 'MTDNA_SERVER_2:INDEX'

Caused by:
  Process `MTDNA_SERVER_2:INDEX` terminated with an error exit status (1)

Command executed:

  samtools faidx mt_contigs.fasta
        samtools dict mt_contigs.fasta      -o mt_contigs.dict

Command exit status:
  1

Command output:

Command error:
  ERROR: Unknown option: --no-home

**Comment by seppinho** [comment]
Thanks. I was able to execute it on singularity without errors. Can you copy/paste the error message from the work directory (work/be/5d16b1/.command.log or .command.err). I believe it could be a singularity problem (--no-home is an option we're not setting in the code). My server runs singularity version 3.8.3. You could also try to run it with Docker if possible.

**Comment by seppinho** [comment]
interesting but again I think this is a singularity problem not a pipeline profile. You could also try with the latest version v2.1.13 but I think this is not related to the pipeline
