### ISSUE TITLE
Is it possible to detect mutations in Mouse chrM

### ISSUE THREAD

**Issue by HuangRuocheng** [genepi/mtdna-server-2#23]
sorry, I am trying mtdna-server-2 in local using docker.

I simply run "nextflow run main.nf -c test_mitohpc_mutserve.config -profile test,development" where config set to bamflies mapping to Mouse mm10. But failed with:

executor >  local (4)
[56/f770f1] MTDNA_SERVER_2:CALCULATE_STATISTICS (2)  [100%] 2 of 2 ✔
[a0/280316] MTDNA_SERVER_2:INPUT_VALIDATION          [100%] 1 of 1, failed: 1
[-        ] MTDNA_SERVER_2:INDEX_CREATION            -
[-        ] MTDNA_SERVER_2:QUALITY_CONTROL           -
[-        ] MTDNA_SERVER_2:MUTSERVE                  -
[-        ] MTDNA_SERVER_2:FILTER_VARIANTS           -
[-        ] MTDNA_SERVER_2:MERGING_VARIANTS          -
[-        ] MTDNA_SERVER_2:VCF_MERGE                 -
[-        ] MTDNA_SERVER_2:HAPLOGROUPS_CONTAMINATION -
[-        ] MTDNA_SERVER_2:COVERAGE_ESTIMATION       -
[-        ] MTDNA_SERVER_2:ANNOTATE                  -
[-        ] MTDNA_SERVER_2:REPORT                    -
[-        ] MTDNA_SERVER_2:SAMPLE_REPORT             -
WARN: Undocumented setting `docker.userEmulation` is not supported any more - please remove it from your config
ERROR ~ Error executing process > 'MTDNA_SERVER_2:INPUT_VALIDATION'

Caused by:
  Process `MTDNA_SERVER_2:INPUT_VALIDATION` terminated with an error exit status (255)

Command executed:

  csvtk concat         -t C.summary.txt KO.summary.txt         -T -o sample_statistics.txt         --num-cpus 1
  
  csvtk concat         -t C.mapping.txt KO.mapping.txt         -T -o sample_mappings.txt         --num-cpus 1
  
  java -jar /opt/mutserve/mutserve.jar stats         --input sample_statistics.txt         --mapping sample_mappings.txt         --detection-limit 0.03          --reference rcrs          --baseQ 20        --mapQ 20         --alignQ 30         --output-excluded-samples excluded_samples.txt         --output-contig contig.txt         --tool mutserve
  
  # delete excluded_samples from BAM input channel directly
  awk -v q='"' '{print "rm " q $1 q }' excluded_samples.txt | sh
  
  python -m json.tool cloudgene.report.json

Command exit status:
  255

Command output:
  
  mtDNA Variant Detection v2.0.1
  https://github.com/seppinho/mutserve
  (c) Sebastian Schoenherr, Hansi Weissensteiner, Lukas Forer
  [stats, --input, sample_statistics.txt, --mapping, sample_mappings.txt, --detection-limit, 0.03, --reference, rcrs, --baseQ, 20, --mapQ, 20, --alignQ, 30, --output-excluded-samples, excluded_samples.txt, --output-contig, contig.txt, --tool, mutserve]
  
  
  ERROR: No valid mtDNA contigs detected.

Command error:
  
  mtDNA Variant Detection v2.0.1
  https://github.com/seppinho/mutserve
  (c) Sebastian Schoenherr, Hansi Weissensteiner, Lukas Forer
  [stats, --input, sample_statistics.txt, --mapping, sample_mappings.txt, --detection-limit, 0.03, --reference, rcrs, --baseQ, 20, --mapQ, 20, --alignQ, 30, --output-excluded-samples, excluded_samples.txt, --output-contig, contig.txt, --tool, mutserve]
  
  
  ERROR: No valid mtDNA contigs detected.

Work dir:
  /home/Group/dna/dnapipe_v3/env_gatk4/mtdna-server-2-2.1.12/work/a0/28031637a0f03345fa16cd16486d5a

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
 
 
 I think maybe I should change reference in somewhere...

**Comment by HuangRuocheng** [comment]
I have changed

files/rcrs_mutserve.fasta content to mm10 chrM sequence
modules/local/calculate_statistics.nf 16569 to 16299, which is the length of mm10 chrM sequence

yet still get the following error in MutServe:

java -Xmx1024M -jar /opt/mutserve/mutserve.jar call C.sub.bam --reference rcrs_mutserve.fasta --output zzztest.vcf 

mtDNA Variant Detection v2.0.1
https://github.com/seppinho/mutserve
(c) Sebastian Schoenherr, Hansi Weissensteiner, Lukas Forer
[call, C.sub.bam, --reference, rcrs_mutserve.fasta, --output, zzztest.vcf]
  ?  C.sub.bam[>-------------------------------------][00:00:00]
java.lang.IllegalArgumentException: Invalid reference index -1
	at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:555)
	at genepi.mut.tasks.VariantCallingTask.run(VariantCallingTask.java:130)
	at lukfor.progress.tasks.Task.call(Task.java:39)
	at lukfor.progress.tasks.Task.call(Task.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.Exception: Invalid reference index -1
	at genepi.mut.tasks.VariantCallingTask.run(VariantCallingTask.java:134)
	at lukfor.progress.tasks.Task.call(Task.java:39)
	at lukfor.progress.tasks.Task.call(Task.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Variant Calling failed. Mutserve terminated.

where shows  Invalid reference index -1.

I am trying Mutect2 option in mtdna-server-2 in local using docker now, still running.

I guess if it is because some human chrM length is coded into mutserve.jar

**Comment by seppinho** [comment]
Hi, correct. We are focusing on human mitochondrial DNA. BUT If you have a valid BAM file you could still run it with your data and add the ```--contig-name XX```option and the ```--reference XX.fasta```to mutserve.

**Please keep in mind that all annotations etc are only for human mtDNA.**

**Comment by HuangRuocheng** [comment]
OK, thank you very much! I will try it out.

ps, Mutect2 has completed and as you said the annotations in the final report are linked to human mtDNA.
